name = "animehunt-backend"
main = "src/index.js"

# âœ… IMPORTANT (latest runtime support)
compatibility_date = "2024-11-01"

# âœ… REQUIRED for jwt, bcrypt, buffer, crypto
compatibility_flags = ["nodejs_compat"]

# ================= DATABASE (Primary - Cloudflare D1) =================

[[d1_databases]]
binding = "DB"
database_name = "animehunt"
database_id = "67cb7fff-a69c-4f86-bd86-9b91dd3d2a79"

# ================= ENV VARIABLES =================

[vars]

# ðŸ” JWT SECRET
JWT_SECRET = "$2a$12$JGDs8IjDGgHAV9swobV8gecyMQFcJwwtcvAXRgnqCntKG6nV8l2EC"

# ðŸ‘¤ ADMIN LOGIN
ADMIN_USERNAME = "anime_moderator_007"

# ðŸ”‘ PASSWORD HASH (bcrypt)
ADMIN_PASSWORD_HASH = "$2a$12$JGDs8IjDGgHAV9swobV8gecyMQFcJwwtcvAXRgnqCntKG6nV8l2EC"

# ðŸ–¼ ImageKit
IMAGEKIT_PUBLIC_KEY = "public_29SqhkCUDesPjYpcKrAS5aFuSkc="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/av2cevzsyi"
IMAGEKIT_PRIVATE_KEY = "private_5RhpDsMuLtxnkYONYmJtS9EiPlI="

# ðŸ—„ Turso (Replica DB - LibSQL)
TURSO_URL = "libsql://animehunt-animehunt1.aws-ap-south-1.turso.io"
TURSO_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODA5OTQzMDYsImlkIjoiMDE5ZWFiODctYzgwMS03OWUyLWE4ZTgtZDdmZmYwYzJhOWFlIiwicmlkIjoiMmRmY2FkYzYtNDFjZC00NWMyLWI4NDUtOTZiOTNjYTg3OGVhIn0.ZRUFwzEjXzrHR6TTo8XZHcoZ3avCnnjb9GQhXKWiPqD7-xNgt51v3VpcXweVq5WPSSZEoAr2LXvU9ULaqPriBA"

# ðŸ—„ Supabase (Replica DB - PostgreSQL)
SUPABASE_URL = "https://ahuwijnulrqsrdnzphds.supabase.co"
SUPABASE_KEY = "sb_publishable_VHHITPpDdy_pKBvWDk2Iiw_7x0Bu51c"

# ================= CRON =================

[triggers]
crons = ["*/5 * * * *"]
