name = "animehunt-backend"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "animehunt"
database_id = "YOUR_D1_DATABASE_ID"

[vars]
JWT_SECRET = "CHANGE_THIS_TO_RANDOM_64_CHAR_SECRET"
ADMIN_USERNAME = "anime_moderator_007"
ADMIN_PASSWORD_HASH = "$2a$12$JGDs8IjDGgHAV9swobV8gecyMQFcJwwtcvAXRgnqCntKG6nV8l2EC"

IMAGEKIT_PUBLIC_KEY = "YOUR_PUBLIC_KEY"
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/YOUR_ID"

[triggers]
crons = ["*/10 * * * *"]
